name: Backend CI

on:
  pull_request: 
    branches: [ develop, release, main ]
    types: [ opened, reopened ]

jobs:
  # ----------------------------
  # 1. Build (테스트 제외)
  # ----------------------------
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      base: ${{ steps.mera.ouputs.base }}

    steps:
      - uses: actions/checkout@v4

      - name: Set meta
        id: meta
        run: echo "short_sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

      - name: Setup java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '17'
          
      - name: Build (no test)
        run: ./gradlew build -x test

      - name: Upload jar (temporary for downstream job)
        uses: actions/upload-artifact@v4
        with:
          name: be-jar_${{ steps.meta.outputs.short_sha }}
          path: build/libs/*.jar
          retention-days: 1

  # ----------------------------
  # 2. Test
  # ----------------------------
  test: 
    name: Test (unit/integration)
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.base_ref != 'main'}}
    steps: 
      - uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with: 
          distribution: 'temurin'
          java-version: '17'

      # develop: 단위 테스트
      - name: Unit test (develop only)
        if: ${{ github.base_ref == 'develop' }}
        run: ./gradlew test
      
      # develop / release: 통합 테스트
      - name: Intergration test (develop/release)
        if: ${{ github.base_ref == 'develop' || github.base_ref == 'release' }}
        run: ./gradlew integrationTest

      # develop: 커버리지 측정
      - name: JaCoCo verification (develop only)
        if: ${{ github.base_ref == 'develop' }}
        env:
          COVERAGE_MIN: '0,0'
        run: ./gradlew test jacocoTestReport jacocoTestCoverageVerification -PCOVERAGE_MIN=${{ env.COVERAGE_MIN }}
  
  # ----------------------------
  # 3. Static Analysis
  # ----------------------------
  static_analysis:
    name: Static Analysis (Sonar Cloud)
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.base_ref == 'develop' || github.base_ref == 'release' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Sonar Cloud scan 
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run:
          ./gradlew sonar 

  # ----------------------------
  # 4. Artifacts (develop / release)
  # ----------------------------
  artifacts:
    name: Upload Verified Artifact (develop, release)
    runs-on: ubuntu-latest
    needs: [build, test, static_analysis]
    if: ${{ github.base_ref == 'develop' || github.base_ref == 'release' }}
    steps: 
      - name: Set build metadata
        id: meta
        run: echo "short_sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        
      - name: Download built jar 
        uses: actions/download-artifact@v4
        with:
          name: be-jar_${{ steps.meta.outputs.short_sha }}
          path: artifact
      
      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: be-jar_${{ steps.meta.outputs.short_sha }}
          path: artifact/*.jar
          retention-days: ${{ github.base_ref == 'develop' && 90 || 30}}

    main_archive:
      name: Archive release to S3
      runs-on: ubuntu-latest
      needs: build
      if: ${{ github.base_ref == 'main' }}

      steps:
        - name: Set meta
          id: meta
          run: |
            echo "timestamp=${date -u + '%Y%m%d-%H%M%S'}" >> $GITHUB_OUTPUT
            echo "short_sha=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT
        
        - name: Download built jar
          uses: actions/download-artifact@v4
          with: 
            name: be-jar_${{ steps.meta.outputs.short_sha }}
            path: artifact

        - name: Configure AWS credentials 
          uses: aws-actions/configure-aws-credentials@v4
          with:
            role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
            aws-region: ap-northeast-2

        - name: Upload jar to S3
          env:
            BUCKET: ${{ secrets.RELEASE_BUCKET }}
            PREFIX: releases/${{ steps.meta.outputs.timestamp }}_${{ steps.meta.outputs.short_sha }}
          run: |
            aws s3 cp artifact/ \
              s3://$BUCKET/$PREFIX/backend/ \
              --recursive \
              --exclude "*" \
              --include "*.jar"
