name: Spring Boot CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 
        
      - name: Build with Gradle
        working-directory: ./app/backend
        run: ./gradlew clean build -x test
        
      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Generate image tag
        id: meta
        run: |
          echo "tag=$(date -u +'%Y%m%d%H%M%S')" >> "$GITHUB_OUTPUT"

      - name: Build and Push Docker Image
        working-directory: ./app/backend
        run: |
          IMAGE="${{ secrets.DOCKER_USERNAME }}/backend-deploy:${{ steps.meta.outputs.tag }}"
          docker build --platform linux/amd64 -t "$IMAGE" . 
          docker push "$IMAGE"

  deploy:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      IMAGE_TAG: ${{ needs.build-and-push-image.outputs.image_tag }}

    steps:
      - name: Prepare SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
        
      - name: Deploy to EC2 via Docker Compose
        run: | 
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "DOCKER_USERNAME='${DOCKER_USERNAME}' IMAGE_TAG='${IMAGE_TAG}' sudo -E bash -s" << 'EOF'
            echo "DOCKER_USERNAME=$DOCKER_USERNAME"
            echo "IMAGE_TAG=$IMAGE_TAG"
            cd /home/${{ secrets.SERVER_USER }}
            docker compose pull
            docker compose up -d
            docker compose ps
            docker compose images
          EOF